on:
  workflow_call:

jobs:
  lint:
    name: "Run ajv JSON validator"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ajv JSON validator
        run: npm run json:check

  schema-docs:
    name: "Render Schema Docs"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: render-json-schema
        uses: RMI-PACTA/actions/actions/json-schema/render-docs@main
        with:
          input-files: "public/schema.json"
          outputs: "public/schema.html"
          output-format: html
